# Generated by Django 5.0.6 on 2024-08-24 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
