# Generated by Django 5.0.6 on 2024-08-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_delete_registration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(default=None, max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("is_verified", models.BooleanField(default=False)),
                ("token", models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
