# Generated by Django 5.0.6 on 2024-08-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="password",
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name="registration",
            name="username",
            field=models.CharField(default=None, max_length=25),
        ),
    ]
