# Generated by Django 5.0.6 on 2024-08-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_registration_password_alter_registration_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="registration",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.AlterField(
            model_name="registration",
            name="username",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
