# Generated by Django 5.0.6 on 2024-08-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_registration_last_login_alter_registration_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
