# Generated by Django 5.0.6 on 2024-08-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_registration_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
