# Generated by Django 5.0.6 on 2024-08-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_registration_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
