# Generated by Django 5.0.6 on 2024-08-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_registration_groups_registration_user_permissions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="registration",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
