# Generated by Django 5.0.6 on 2024-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_registration_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
