# Generated by Django 5.0.6 on 2024-06-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("developian", "0002_reflection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reflection",
            old_name="data_added",
            new_name="date_added",
        ),
    ]
